"""
Django settings for gdaypunchbackend project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import json

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4^ym%_+o+)*m(l8-+6d(=+0uaayu9tea2n7q2g*_gl&nbpc*q&'

# SECURITY WARNING: don't run with debug turned on in production!
if 'DEVENV' in os.environ:
    DEBUG = True

ALLOWED_HOSTS = [
    "gdaypunch.com",
    ".gdaypunch.com",
    "gdaypunch.elasticbeanstalk.com",
    "gday-punch-web-dev.us-west-2.elasticbeanstalk.com",
    ".gday-punch-web-dev.us-west-2.elasticbeanstalk.com",
    "www.beta-gdaypunch.com",
    "beta-gdaypunch.com",
    "localhost",
    "0.0.0.0",
    "192.168.1.100",
    "192.168.1.103",
    "172.31.15.249",
    "172.31.6.161",
]


def is_ec2_linux():
    """Detect if we are running on an EC2 Linux Instance
       See http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/identify_ec2_instances.html
    """
    if os.path.isfile("/sys/hypervisor/uuid"):
        with open("/sys/hypervisor/uuid") as f:
            uuid = f.read()
            return uuid.startswith("ec2")
    return False


def get_linux_ec2_private_ip():
    """Get the private IP Address of the machine if running on an EC2 linux server"""
    from urllib.request import urlopen
    if not is_ec2_linux():
        return None
    try:
        response = urlopen(
            'http://169.254.169.254/latest/meta-data/local-ipv4')
        return response.read()
    except:
        return None
    finally:
        if response:
            response.close()


# ElasticBeanstalk healthcheck sends requests with host header = internal ip
# So we detect if we are in elastic beanstalk,
# and add the instances private ip address
private_ip = get_linux_ec2_private_ip()
if private_ip:
    ALLOWED_HOSTS.append(private_ip.decode('UTF-8'))

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'gdaypunchbackend.gdaypunchapi',
    'gdaypunchbackend',
    'gdaypunchwebapp',
    'rest_framework_swagger',
]

AUTH_USER_MODEL = 'gdaypunchapi.User'

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'post_user': '5/minute',
        'post_anon': '3/minute',
        'get_anon': '100/minute',
        'post_user': '5/minute',
        'get_user': '150/minute',
        'anon': '100/day',
        'user': '1000/day',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'PAGE_SIZE': 10
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_currentuser.middleware.ThreadLocalUserMiddleware',
]

ROOT_URLCONF = 'gdaypunchbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gdaypunchbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# Local SQLite3 database
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# To start postgres
# pg_ctl -D /usr/local/var/postgres start

# To access PSQL on local machine + commands to instantiate database
# psql postgres // Enter PSQL CLI
# create database gdaypunch; // Create database
# create role gdayuser with login password 'gdaypassword'; // Create user + password
# \q // exit PSQL CLI

if 'DEVENV' in os.environ:
    dbconfig = "./gday-db-config.json"
else:
    dbconfig = '/opt/app/gday-db-config.json'

SETTINGS = None
with open(dbconfig) as f:
    SETTINGS = json.load(f)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': SETTINGS['RDS_DB_NAME'],
        'USER': SETTINGS['RDS_USERNAME'],
        'PASSWORD': SETTINGS['RDS_PASSWORD'],
        'HOST': SETTINGS['RDS_HOSTNAME'],
        'PORT': SETTINGS['RDS_PORT'],
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

if 'DEVENV' in os.environ:
    STATIC_ROOT = os.path.join(BASE_DIR, "gdaypunchbackend/public/static/")
else:
    STATIC_ROOT = "opt/app/gdaypunchbackend/public/static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "gdaypunchwebapp/gdaypunchreact/public/static/"),
    os.path.join(BASE_DIR, "gdaypunchbackend/static/"),
    os.path.join(BASE_DIR, "gdaypunchbackend/build/"),
]

# Static file directory in the React app
STATIC_URL = '/static/'
