# Generated by Django 3.0.4 on 2020-05-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0002_like_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='pdf',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='manga',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
