# Generated by Django 3.0.4 on 2020-10-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0003_auto_20200512_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='cover',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
