# Generated by Django 3.0.4 on 2020-10-22 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0004_manga_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionType',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'issue'), (2, 'manga'), (3, 'illustration')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('collectionType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.CollectionType')),
                ('mangas', models.ManyToManyField(to='gdaypunchapi.Manga')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
