# Generated by Django 3.0.4 on 2021-03-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0008_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='prompt',
            field=models.TextField(max_length=50),
        ),
    ]
