# Generated by Django 3.0.4 on 2021-03-27 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0009_auto_20210319_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptType',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'subject'), (2, 'panel_style')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='prompt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prompt',
            name='promptType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.PromptType'),
            preserve_default=False,
        ),
    ]
