# Generated by Django 3.0.4 on 2021-03-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0010_auto_20210327_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
