# Generated by Django 3.0.4 on 2021-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0011_prompt_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontype',
            name='name',
            field=models.TextField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompttype',
            name='name',
            field=models.TextField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
