# Generated by Django 3.0.4 on 2021-04-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0012_auto_20210401_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontype',
            name='name',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='prompttype',
            name='name',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
