# Generated by Django 3.0.4 on 2021-04-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0013_auto_20210401_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttype',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'subject'), (2, 'panel_style'), (2, 'panel_framing')], primary_key=True, serialize=False),
        ),
    ]
