# Generated by Django 3.0.4 on 2021-06-09 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0015_auto_20210608_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_product_id', models.TextField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('title', models.TextField(blank=True, max_length=70, unique=True)),
                ('image', models.TextField(blank=True, max_length=100)),
                ('sale_price', models.IntegerField(blank=True)),
                ('visible', models.BooleanField(default=False)),
                ('stock', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'physical'), (2, 'digital'), (3, 'subscription')], primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permalink', models.TextField(blank=True, max_length=100)),
                ('title', models.TextField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('rating', models.IntegerField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('email', models.TextField(max_length=100)),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('address_line_1', models.TextField(max_length=50)),
                ('address_line_2', models.TextField(blank=True, max_length=50)),
                ('city', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('postcode', models.TextField(max_length=50)),
                ('country', models.TextField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('billing_same_address', models.BooleanField(default=True)),
                ('billing_first_name', models.TextField(max_length=50)),
                ('billing_last_name', models.TextField(max_length=50)),
                ('billing_address_line_1', models.TextField(max_length=50)),
                ('billing_address_line_2', models.TextField(blank=True, max_length=50)),
                ('billing_city', models.TextField(max_length=50)),
                ('billing_state', models.TextField(max_length=50)),
                ('billing_postcode', models.TextField(max_length=50)),
                ('billing_country', models.TextField(max_length=50)),
                ('billing_number', models.IntegerField()),
                ('last_four', models.IntegerField()),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Product')),
            ],
        ),
    ]
