# Generated by Django 3.0.4 on 2021-06-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0017_auto_20210610_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstripeprices',
            old_name='price',
            new_name='stripe_price',
        ),
    ]
