# Generated by Django 3.0.4 on 2021-06-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0018_auto_20210610_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(
                default='1', on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.ProductType'),
            preserve_default=False,
        ),
    ]
