# Generated by Django 3.0.4 on 2021-06-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0019_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.FloatField(blank=True),
        ),
    ]
