# Generated by Django 3.0.4 on 2021-06-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0020_auto_20210611_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'super'), (2, 'admin'), (3, 'prompts'), (4, 'products'), (5, 'twitter'), (6, 'instagram')], primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='privileges',
            field=models.ManyToManyField(blank=True, to='gdaypunchapi.Privileges'),
        ),
    ]
