# Generated by Django 3.0.4 on 2021-06-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0021_auto_20210611_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductStripePrices',
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_prices',
            field=models.ManyToManyField(blank=True, to='gdaypunchapi.StripePrice'),
        ),
    ]
