# Generated by Django 3.0.4 on 2021-06-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0022_auto_20210613_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='last_selected',
            field=models.DateField(blank=True, null=True),
        ),
    ]
