# Generated by Django 3.0.4 on 2021-06-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0023_prompt_last_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripeprice',
            old_name='price',
            new_name='price_id',
        ),
        migrations.AddField(
            model_name='stripeprice',
            name='price_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
