# Generated by Django 3.0.4 on 2021-06-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0024_auto_20210623_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeprice',
            name='price_amount',
            field=models.FloatField(),
        ),
    ]
