# Generated by Django 3.0.4 on 2021-06-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0025_auto_20210623_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeprice',
            name='price_title',
            field=models.TextField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
