# Generated by Django 3.0.4 on 2021-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0026_stripeprice_price_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
