# Generated by Django 3.0.4 on 2021-07-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0028_auto_20210627_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=50)),
                ('reason', models.TextField(choices=[(1, 'general'), (2, 'order'), (3, 'advertising'), (4, 'subscription'), (5, 'subscription_cancellation'), (6, 'unsubscribe')], default=1, max_length=30)),
                ('message', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
