# Generated by Django 3.0.4 on 2021-07-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0029_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.TextField(choices=[('general', 'General'), ('order', 'Order'), ('advertising', 'Advertising'), ('subscription', 'Subscription'), ('subscription_cancellation', 'SubCancellation'), ('unsubscribe', 'EmailUnsubscribe')], default='general', max_length=30),
        ),
    ]
