# Generated by Django 3.0.4 on 2021-07-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0030_auto_20210712_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeprice',
            name='price_type',
            field=models.TextField(default='one_time', max_length=20),
        ),
    ]
