# Generated by Django 3.0.4 on 2021-07-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0031_stripeprice_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
