# Generated by Django 3.0.4 on 2021-07-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0032_product_active_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
