# Generated by Django 3.0.4 on 2021-07-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0034_auto_20210713_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
