# Generated by Django 3.0.4 on 2021-07-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0035_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manga',
            field=models.ManyToManyField(blank=True, to='gdaypunchapi.Manga'),
        ),
    ]
