# Generated by Django 3.0.4 on 2021-07-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0036_product_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
