# Generated by Django 3.0.4 on 2021-07-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0037_manga_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='age_rating',
            field=models.TextField(choices=[('all_ages', 'All Ages'), ('teens', 'Teens'), ('young_adults', 'Young Adults'), ('adults', 'Adults')], default='teens', max_length=30),
        ),
    ]
