# Generated by Django 3.0.4 on 2021-07-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0038_manga_age_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active_price',
        ),
    ]
