# Generated by Django 3.0.4 on 2021-08-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0040_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, to='gdaypunchapi.Product'),
        ),
        migrations.AlterField(
            model_name='prompttype',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'subject'), (2, 'panel_style'), (3, 'panel_framing')], primary_key=True, serialize=False),
        ),
    ]
