# Generated by Django 3.0.4 on 2021-08-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0041_auto_20210806_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripe_email',
            field=models.TextField(max_length=70),
        ),
    ]
