# Generated by Django 3.0.4 on 2021-08-24 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0044_auto_20210814_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.TextField(choices=[('subscribed_only', 'Subscribed Only'), ('purchased_subscribed', 'Purchased and Subscribed'), ('checkout_subscribed', 'Subscribed at Checkout'), ('not_subscribed', 'Not Subscribed')], default='subscribed_only', max_length=30)),
                ('number', models.IntegerField()),
                ('email', models.TextField(max_length=100)),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('address_line_1', models.TextField(max_length=50)),
                ('address_line_2', models.TextField(blank=True, max_length=50)),
                ('city', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('postcode', models.TextField(max_length=50)),
                ('country', models.TextField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
