# Generated by Django 3.0.4 on 2021-08-24 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0045_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='gp_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Customer'),
        ),
    ]
