# Generated by Django 3.0.4 on 2021-08-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0046_stripecustomer_gp_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='number',
        ),
    ]
