# Generated by Django 3.0.4 on 2021-08-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0047_remove_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.TextField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.TextField(max_length=50),
        ),
    ]
