# Generated by Django 3.0.4 on 2021-08-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0048_auto_20210824_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribed',
        ),
    ]
