# Generated by Django 3.0.4 on 2021-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0050_resetpasswordsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordsession',
            name='created_date',
            field=models.TextField(default='2021-08-28 14:36:04', max_length=40),
        ),
    ]
