# Generated by Django 3.0.4 on 2021-08-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0051_auto_20210828_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordsession',
            name='verified_token',
            field=models.TextField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='resetpasswordsession',
            name='created_date',
            field=models.TextField(default='2021-08-28 16:02:15', max_length=40),
        ),
    ]
