# Generated by Django 3.0.4 on 2021-09-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0052_auto_20210828_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.TextField(default='apMzv5QVIb-5cup6feifr8IxUXypg1xA93lnB1NKzW4', max_length=50),
        ),
        migrations.AlterField(
            model_name='resetpasswordsession',
            name='created_date',
            field=models.TextField(default='2021-09-03 15:41:03', max_length=40),
        ),
    ]
