# Generated by Django 3.0.4 on 2021-09-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0053_auto_20210903_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordsession',
            name='created_date',
            field=models.TextField(default='2021-09-03 15:45:07', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.TextField(default='Hi9soMbFqnaQ1Nk6c5Z4MWdsF4dmv0sUK7CC7Jcg2TmcwykAzyvaifLJ4HFrm6YhNVjc3oPRAyS3y5u0UdMRSwNisGgrm0PIzfB4TH7IpN8x5lc', max_length=50),
        ),
    ]
