# Generated by Django 3.0.4 on 2021-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0054_auto_20210903_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordsession',
            name='created_date',
            field=models.TextField(default='2021-09-03 15:46:24', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.TextField(default='zNYo6U-zwMEbLId7Uc68p-55CVOiWGeRQVygtbfbljLpC6idM1YPC60gHVNMAf8KDlokbS30S36SQDLJERF86VHVkWtAczaffKGbMlP8N3KQ5kNa5YztUhWCN-d7t5KHXvbOyGu_QrxStHkAwriMEKuEls9HYhjLqpebnNgDocLl2B67XJlb_aWMERqlp9Tr5ksIDVlKC5O8HZRp_VFGhnmzy9Ua__zSgCTyE2gX07tMHaDnGlyqgI_XKMQOIYJkWCMDSpnszKPFREf_Dbosogn0n9MxiX5ebJNSJkwolioeaNR9U66J1jpOkCYQMmDj9l2ii4MmTWLYnQffQcKHuQp5VG6L1odbVDGLlpfmOhIh9AgWqTd9v7axZG_-GmO0JSd5uD7utml1x7sp4NpqKb1-iKtheey7eFWn8qxVJpInzCoPvgRFIdWUU9LZDsIDSdGUmacLLDw-I8oGZHKwJABJ-0oLnT2rnUy24ZLykqvaXsFOTxyu9dnQPjY', max_length=50),
        ),
    ]
