# Generated by Django 3.0.4 on 2021-09-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0055_auto_20210903_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
        migrations.AlterField(
            model_name='resetpasswordsession',
            name='created_date',
            field=models.TextField(default='2021-09-03 15:48:06', max_length=40),
        ),
    ]
