# Generated by Django 3.0.4 on 2021-09-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0056_auto_20210903_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordsession',
            name='created_date',
            field=models.TextField(max_length=40),
        ),
    ]
