# Generated by Django 3.0.4 on 2021-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0057_auto_20210903_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
