# Generated by Django 3.0.4 on 2021-09-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0058_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent',
            field=models.TextField(max_length=70, null=True),
        ),
    ]
