# Generated by Django 3.0.4 on 2021-09-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0059_order_payment_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_intent',
        ),
    ]
