# Generated by Django 3.0.4 on 2021-09-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0060_remove_order_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_email',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
