# Generated by Django 3.0.4 on 2021-09-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0061_order_billing_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address_line_1',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_city',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_email',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_first_name',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_last_name',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_postcode',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_state',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
