# Generated by Django 3.0.4 on 2021-09-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0062_auto_20210908_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, default=None, to='gdaypunchapi.Product'),
        ),
    ]
