# Generated by Django 3.0.4 on 2021-09-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0064_auto_20210908_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exp_month',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='exp_year',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_four',
            field=models.TextField(max_length=10),
        ),
    ]
