# Generated by Django 3.0.4 on 2021-09-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0065_auto_20210909_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_number',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.TextField(max_length=20),
        ),
    ]
