# Generated by Django 3.0.4 on 2021-09-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0066_auto_20210909_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products_qty',
            field=models.TextField(default='{}', max_length=500),
        ),
    ]
