# Generated by Django 3.0.4 on 2021-09-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0067_auto_20210909_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('declined', 'Declined'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=30),
        ),
    ]
