# Generated by Django 3.0.4 on 2021-09-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0069_auto_20210910_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_last_name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
