# Generated by Django 3.0.4 on 2021-09-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0070_auto_20210911_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('declined', 'Declined'), ('purchased', 'Purchased'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatusupdate',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('declined', 'Declined'), ('purchased', 'Purchased'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=30),
        ),
    ]
