# Generated by Django 3.0.4 on 2021-09-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0071_auto_20210911_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.TextField(choices=[('physical', 'Physical'), ('digital', 'Digital'), ('subscription', 'Subscription')], default='physical', max_length=30),
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
