# Generated by Django 3.0.4 on 2021-09-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0073_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
