# Generated by Django 3.0.4 on 2021-09-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0074_order_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('date_created', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
