# Generated by Django 3.0.4 on 2021-09-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0075_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.TextField(choices=[('percent', 'Percent'), ('amount', 'Amount')], default='percent', max_length=30),
        ),
    ]
