# Generated by Django 3.0.4 on 2021-09-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0076_auto_20210912_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.TextField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], default='percentage', max_length=30),
        ),
    ]
