# Generated by Django 3.0.4 on 2021-09-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0078_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
