# Generated by Django 3.0.4 on 2021-09-15 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0079_auto_20210914_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.TextField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
