# Generated by Django 3.0.4 on 2021-09-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0080_auto_20210915_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='last_selected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
