# Generated by Django 3.0.4 on 2021-09-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0083_auto_20210915_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatusupdate',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
