# Generated by Django 3.0.4 on 2021-09-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0084_orderstatusupdate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatusupdate',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
