# Generated by Django 3.0.4 on 2021-09-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0085_auto_20210918_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='secret',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
