# Generated by Django 3.0.4 on 2021-09-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0086_order_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dig_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='mag_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripeprice',
            name='charge_type',
            field=models.TextField(choices=[('per_release', 'Per Release'), ('fixed_interval', 'Fixed Interval')], default='fixed_interval', max_length=30),
        ),
        migrations.AddField(
            model_name='stripeprice',
            name='month_interval',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.TextField(choices=[('physical', 'Physical'), ('digital', 'Digital'), ('physical_collection', 'Physical Collection'), ('digital_collection', 'Digital Collection'), ('mixed_collection', 'Mixed Collection'), ('mag_subscription', 'Magazines Subscription'), ('dig_subscription', 'Digitals Subscription')], default='physical', max_length=30),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionType',
        ),
    ]
