# Generated by Django 3.0.4 on 2021-09-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0087_auto_20210924_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Product')),
            ],
        ),
    ]
