# Generated by Django 3.0.4 on 2021-09-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0088_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeprice',
            name='charge_type',
        ),
    ]
