# Generated by Django 3.0.4 on 2021-09-27 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0089_remove_stripeprice_charge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_line_1',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postcode',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscribed',
            field=models.TextField(choices=[('subscribed_only', 'Subscribed Only'), ('purchased_subscribed', 'Purchased and Subscribed'), ('checkout_subscribed', 'Subscribed at Checkout'), ('not_subscribed', 'Not Subscribed')], default='purchased_subscribed', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line_1',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.TextField(choices=[('physical', 'Physical'), ('digital', 'Digital'), ('subscription', 'Subscription'), ('physical_collection', 'Physical Collection'), ('digital_collection', 'Digital Collection'), ('mixed_collection', 'Mixed Collection'), ('mag_subscription', 'Magazines Subscription'), ('dig_subscription', 'Digitals Subscription')], default='physical', max_length=30),
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
