# Generated by Django 3.0.4 on 2021-09-27 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0090_auto_20210927_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='saved_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
