# Generated by Django 3.0.4 on 2021-10-01 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0091_save_saved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Purchase'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscribed',
            field=models.TextField(choices=[('subscribed_only', 'Subscribed Only'), ('download_subscribed', 'Downloaded Resource and Subscribed'), ('purchased_subscribed', 'Purchased and Subscribed'), ('checkout_subscribed', 'Subscribed at Checkout'), ('not_subscribed', 'Not Subscribed')], default='purchased_subscribed', max_length=30),
        ),
    ]
