# Generated by Django 3.0.4 on 2021-10-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0092_auto_20211001_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscribed',
            field=models.TextField(choices=[('subscribed_only', 'Subscribed Only'), ('download_subscribed', 'Downloaded Resource and Subscribed'), ('purchased_subscribed', 'Purchased and Subscribed'), ('checkout_subscribed', 'Subscribed at Checkout'), ('not_subscribed', 'Not Subscribed'), ('unsubscribed', 'Unsubscribed')], default='purchased_subscribed', max_length=30),
        ),
    ]
