# Generated by Django 3.0.4 on 2021-10-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0093_auto_20211002_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privileges',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'super'), (2, 'admin'), (3, 'prompts'), (4, 'products'), (5, 'twitter'), (6, 'instagram'), (7, 'shop_tester')], primary_key=True, serialize=False),
        ),
    ]
