# Generated by Django 3.0.4 on 2021-10-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0094_auto_20211007_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='page_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
