# Generated by Django 3.0.4 on 2021-10-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0095_manga_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='japanese_reading',
            field=models.BooleanField(default=True),
        ),
    ]
