# Generated by Django 3.0.4 on 2021-10-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0096_manga_japanese_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=70)),
                ('author', models.TextField(max_length=70)),
                ('img', models.TextField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='VotingRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.IntegerField()),
                ('item1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item1_voting_round_set', to='gdaypunchapi.VotingItem')),
                ('item10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item10_voting_round_set', to='gdaypunchapi.VotingItem')),
                ('item2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item2_voting_round_set', to='gdaypunchapi.VotingItem')),
                ('item3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item3_voting_round_set', to='gdaypunchapi.VotingItem')),
                ('item4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item4_voting_round_set', to='gdaypunchapi.VotingItem')),
                ('item5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item5_voting_round_set', to='gdaypunchapi.VotingItem')),
                ('item6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item6_voting_round_set', to='gdaypunchapi.VotingItem')),
                ('item7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item7_voting_round_set', to='gdaypunchapi.VotingItem')),
                ('item8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item8_voting_round_set', to='gdaypunchapi.VotingItem')),
                ('item9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item9_voting_round_set', to='gdaypunchapi.VotingItem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.IntegerField(null=True)),
                ('item2', models.IntegerField(null=True)),
                ('item3', models.IntegerField(null=True)),
                ('item4', models.IntegerField(null=True)),
                ('item5', models.IntegerField(null=True)),
                ('item6', models.IntegerField(null=True)),
                ('item7', models.IntegerField(null=True)),
                ('item8', models.IntegerField(null=True)),
                ('item9', models.IntegerField(null=True)),
                ('item10', models.IntegerField(null=True)),
                ('purchase_reason', models.TextField(choices=[('friend', 'Friend'), ('sales_call', 'Sales Call'), ('web_search', 'Web Search'), ('amaa_group', 'Anime and Manga Artists Australia Group'), ('fb_page', 'Facebook Page'), ('ig_profile', 'Instagram Profile'), ('tw_profile', 'Twitter Profile'), ('yt_channel', 'YouTube Channel'), ('tt_account', 'TikTok Account'), ('fb_ad', 'Facebook Ad'), ('ig_ad', 'Instagram Ad'), ('library', 'Library'), ('school', 'School'), ('online_store', 'Online Store'), ('comic_store', 'Comic Store'), ('book_store', 'Book Store'), ('posters_flyers', 'Posters and Flyers'), ('other_reason', 'Other')], default='online_store', max_length=30)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Customer')),
                ('voting_round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.VotingRound')),
            ],
        ),
    ]
