# Generated by Django 3.0.4 on 2021-10-11 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0097_vote_votingitem_votinground'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='votinground',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
