# Generated by Django 3.0.4 on 2021-10-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0098_auto_20211011_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='stripe_subscription_id',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
