# Generated by Django 3.0.4 on 2021-10-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0099_stripecustomer_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='exp_month',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='exp_year',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_four',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
