# Generated by Django 3.0.4 on 2021-10-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0100_auto_20211012_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ip',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
