# Generated by Django 3.0.4 on 2021-10-17 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0101_user_last_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permalink', models.TextField(blank=True, max_length=100)),
                ('title', models.TextField(blank=True, max_length=100)),
                ('img', models.TextField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductSEO',
        ),
    ]
