# Generated by Django 3.0.4 on 2021-10-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0103_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='user_list_order',
            field=models.TextField(choices=[('by_id', 'By Id'), ('by_last_login', 'By Last Login')], default='by_id', max_length=30),
        ),
    ]
