# Generated by Django 3.0.4 on 2021-10-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0104_settings_user_list_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.TextField(choices=[('general', 'General'), ('order', 'Order'), ('advertising', 'Advertising'), ('subscription', 'Subscription'), ('subscription_cancellation', 'SubCancellation'), ('unsubscribe', 'EmailUnsubscribe'), ('bug_report', 'Bug Report')], default='general', max_length=30),
        ),
    ]
