# Generated by Django 3.0.4 on 2021-10-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0105_auto_20211021_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.ImageField(null=True, upload_to='user_cover'),
        ),
    ]
