# Generated by Django 3.0.4 on 2021-10-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0107_follow_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='cover',
        ),
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.TextField(choices=[('general', 'General'), ('order', 'Order'), ('advertising', 'Advertising'), ('subscription', 'Subscription'), ('subscription_cancellation', 'SubCancellation'), ('unsubscribe', 'EmailUnsubscribe'), ('bug_report', 'Bug Report'), ('report', 'Report')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='manga',
            name='pdf',
            field=models.ImageField(null=True, upload_to='manga_pdf'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_image'),
        ),
    ]
