# Generated by Django 3.0.4 on 2021-10-26 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0109_auto_20211026_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
