# Generated by Django 3.0.4 on 2021-10-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0111_auto_20211026_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.TextField(blank=True, max_length=30, unique=True),
        ),
    ]
