# Generated by Django 3.0.4 on 2021-11-02 05:05

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0112_auto_20211027_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_store',
        ),
        migrations.AddField(
            model_name='product',
            name='image_store_public',
            field=models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='gdaypunch-resources'), upload_to='product_image_public'),
        ),
        migrations.AddField(
            model_name='user',
            name='image_public',
            field=models.ImageField(null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='gdaypunch-resources'), upload_to='user_profile_public'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
