# Generated by Django 3.0.4 on 2021-10-27 00:25

from django.db import migrations, models
import gdaypunchbackend.gdaypunchapi.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0112_auto_20211027_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.TextField(blank=True, default=gdaypunchbackend.gdaypunchapi.model_utils.create_default_sku, max_length=30, unique=True),
        ),
    ]
