# Generated by Django 3.0.4 on 2021-10-27 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0113_auto_20211027_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_store',
        ),
    ]
