# Generated by Django 3.0.4 on 2021-12-19 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0113_auto_20211102_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='last_viewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='manga',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
