# Generated by Django 3.0.4 on 2022-02-11 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0114_auto_20211219_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('start_order_id', models.IntegerField(blank=True, null=True)),
                ('end_order_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email', models.TextField(blank=True, max_length=50)),
                ('bank_acc_name', models.TextField(blank=True, max_length=50)),
                ('bank_bsb', models.TextField(blank=True, max_length=10)),
                ('bank_acc', models.TextField(blank=True, max_length=20)),
                ('use_paypal', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerOrderRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('processing', 'Payout Processing'), ('succeeded', 'Payout Succeeded'), ('failed', 'Payout Failed'), ('retrying', 'Payout Retrying')], default='processing', max_length=30)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Payout')),
            ],
        ),
    ]
