# Generated by Django 3.0.4 on 2021-11-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0115_auto_20211028_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
