# Generated by Django 3.0.4 on 2022-02-21 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0115_payout_payoutupdate_seller_sellerorderref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gdaypunchapi.Seller'),
        ),
    ]
