# Generated by Django 3.0.4 on 2022-02-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0116_payout_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutupdate',
            name='status',
            field=models.TextField(choices=[('processing', 'Payout Processing'), ('succeeded', 'Payout Succeeded'), ('failed', 'Payout Failed'), ('retrying', 'Payout Retrying')], default='scheduled', max_length=30),
        ),
    ]
