# Generated by Django 3.0.4 on 2022-02-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0117_auto_20220210_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='bank_acc_name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
