# Generated by Django 3.0.4 on 2022-03-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0117_auto_20220227_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='end_order_id',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='start_order_id',
        ),
        migrations.AddField(
            model_name='payout',
            name='end_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='end_order', to='gdaypunchapi.Order'),
        ),
        migrations.AddField(
            model_name='payout',
            name='start_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='start_order', to='gdaypunchapi.Order'),
        ),
    ]
