# Generated by Django 3.0.4 on 2022-03-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0118_auto_20220301_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='end_order',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='start_order',
        ),
        migrations.AddField(
            model_name='payout',
            name='orders',
            field=models.ManyToManyField(blank=True, to='gdaypunchapi.Order'),
        ),
    ]
