# Generated by Django 3.0.4 on 2022-03-04 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdaypunchapi', '0119_auto_20220304_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='amount',
        ),
    ]
